# Generated by Django 4.2.20 on 2025-03-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_customuser_managers_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(max_length=255)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Buyer', 'Buyer'), ('Farmer', 'Farmer')], max_length=100)),
            ],
        ),
    ]
