# Generated by Django 5.1.5 on 2025-03-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('unit_price', models.IntegerField()),
                ('quantity', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('Kg', 'Kilogram'), ('Tons', 'Tons'), ('Qntls', 'Quintals')], max_length=100)),
                ('harvest_date', models.DateField()),
                ('image', models.ImageField(upload_to='farmerProfile/')),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
