# Generated by Django 5.1.5 on 2025-03-01 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('unit_price', models.IntegerField()),
                ('quantity', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('Kg', 'Kilogram'), ('Tons', 'Tons'), ('Qntls', 'Quintals')], max_length=100)),
                ('harvest_date', models.DateField()),
                ('image', models.ImageField(upload_to='farmerProfile/')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='', max_length=255)),
                ('phone_no', models.CharField(default='', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
