# Generated by Django 5.1.5 on 2025-03-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerProfile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserModel',
        ),
    ]
