# Generated by Django 5.1.5 on 2025-03-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmerProfile', '0002_delete_customusermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('unit_price', models.IntegerField()),
                ('unit_quantity', models.CharField(choices=[('Kg', 'Kilogram'), ('Tons', 'Tons'), ('Qntls', 'Quintals')], max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('harvest_date', models.DateField()),
            ],
        ),
    ]
