# Generated by Django 5.1.5 on 2025-03-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerProfile', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_listing',
            name='image',
            field=models.ImageField(default=1234, upload_to='farmerProfile/'),
            preserve_default=False,
        ),
    ]
