# Generated by Django 5.1.5 on 2025-03-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerProfile', '0004_product_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_listing',
            name='description',
            field=models.CharField(default='Best quality crop', max_length=1000),
            preserve_default=False,
        ),
    ]
