# Generated by Django 5.1.5 on 2025-03-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerProfile', '0005_product_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_listing',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
