# Generated by Django 5.1.5 on 2025-03-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerProfile', '0007_alter_product_listing_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_listing',
            old_name='unit_quantity',
            new_name='unit',
        ),
    ]
