# Generated by Django 5.1.5 on 2025-03-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_order_parent_order_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='parent_order',
        ),
    ]
