# Generated by Django 5.1.5 on 2025-03-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_remove_order_parent_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='unit_price',
        ),
    ]
