# Generated by Django 5.1.5 on 2025-03-08 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_remove_order_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
    ]
